title: Benjamin Reyes
url: "https://benji545.github.io"
baseurl: "/personal-website"

markdown: kramdown
#ins_logo: "./bits-logo.png"

favicon: true
favicon_location: "favicon.ico"

tracking_id: #

footer: false
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/personal-website/researcher/"
 - name: "Projects"
   link: "/personal-website/researcher/projects"
 - name: "Contact"
   link: "/personal-website/researcher/contact"
